#define BUILDER_MIN_COST 1
#define BUILDER_MAX_COST 3

#define BUILDER_MIN_PROVIDES 1
#define BUILDER_MAX_PROVIDES 3

#define BUILDER_MIN_PTS 1
#define BUILDER_MAX_PTS 2

#define BUILDER_MIN_COUNT 2

#define BUILDER_MIN_LEVEL 0
  
