#define BUILDER_MIN_COST 1
#define BUILDER_MAX_COST 3

#define BUILDER_MIN_PROVIDES 1
#define BUILDER_MAX_PROVIDES 3

#define BUILDER_MIN_PTS (BUILDER_MIN_LEVEL * 5)
#define BUILDER_MAX_PTS 10

#define BUILDER_MIN_COUNT 2

#define BUILDER_MIN_LEVEL 1
#define BUILDER_MAX_LEVEL NUM_LEVELS
  
